---
- hosts: 192.168.37.106
  tasks:
    - name: Check Cafe Version
      shell: ping 192.168.37.106
      shell: cafebot.py --version
      ignore_errors: true
#      apt: pkg=ansible state=installed update_cathe=true
#      notify: 
#        - start ansible
#
#   
#  handlers:
#    - name: start ansible
#      service: name=nginx state=started
